/**
 * @fileoverview gRPC-Web generated client stub for knut.service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.20.3
// source: service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as service_pb from './service_pb';


export class KnutServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorHello = new grpcWeb.MethodDescriptor(
    '/knut.service.KnutService/Hello',
    grpcWeb.MethodType.UNARY,
    service_pb.HelloRequest,
    service_pb.HelloResponse,
    (request: service_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    service_pb.HelloResponse.deserializeBinary
  );

  hello(
    request: service_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null): Promise<service_pb.HelloResponse>;

  hello(
    request: service_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.HelloResponse) => void): grpcWeb.ClientReadableStream<service_pb.HelloResponse>;

  hello(
    request: service_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.HelloResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/knut.service.KnutService/Hello',
        request,
        metadata || {},
        this.methodDescriptorHello,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/knut.service.KnutService/Hello',
    request,
    metadata || {},
    this.methodDescriptorHello);
  }

}

