package main

// +build ignore

import (
	"log"
	"os"
	"text/template"
	"time"
)

func main() {
	version := os.Getenv("VERSION")
	if version == "" {
		version = "default"
	}

	t := time.Now()

	f, err := os.Create("cmd/version.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
		Version   string
		Date      string
	}{
		Timestamp: t,
		Version:   version,
		Date:      t.Format("2006-01-02"),
	})
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated by go generate at
// {{ .Timestamp }}
package cmd

var (
	version = "{{ .Version }}"
	date = "{{ .Date }}"
)
`))
