name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.19.1"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: cd web && npm install && npm run build
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}